export const WEATHER_DATA_SUCCESS = 'WEATHER_DATA_SUCCESS';
export const WEATHER_DATA_FAIL = 'WEATHER_DATA_FAIL';

export const FETCH_SEARCHED_CITY = 'FETCH_SEARCHED_CITY';
export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';

export const FETCH_HOURLY_DATA = 'HOURLY_DATA_SUCCESS';
